config/routes.rb
Rails.application.routes.draw do

  root 'students#index'
  resources :students do
    member do
      get :delete
    end
  end
  # get 'students/index'
  # get 'students/show'
  # get 'students/new'
  # get 'students/edit'
  # get 'students/delete'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  layout false
  def index
    @students=User.all

    # render json: @students
  end

  def show
    @student=User.find(params[:id])
    # render json: @student
    
  end

  def new
    @student=User.new()
    # render json: @subject
    # @subject=User.new({:first_name => 'Default'})
  end

  def create
    @student=User.new(student_params)
    if @student.save
      # render json: @subject
      redirect_to(students_path)
      
    else
      render('new')

    end
  end

  def edit
    @student=User.find(params[:id])
    # render json:@subject
  end
  def update
    @student=User.find(params[:id])
    # @subject=User.update_attributes(subject_params)
    if @student.update(student_params)
      # render json: @subject
      redirect_to(students_path(@student))
      
    else
      render('edit')

    end
  end
  def delete
    @student=User.find(params[:id])
    # render json: @subject
  end
  def destroy
    @students=User.all
    @student=User.find(params[:id])
    @student.destroy
    # render json: @subjects
    redirect_to(students_path)
  end
  private
  def student_params
    params.required(:user).permit(:name,:email,:phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Code</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/delete.html.erb
<body style="background-color:#ffff99;"><center>

<button><%=link_to("BACK TO LIST",students_path, :class => 'back-link') %></button>

<h1>Delete Student</h1>
<%= form_for(@student,:url => student_path(@student),:method => 'delete')do |f|%>
<p>Are you sure want to delete this student</p>
<p><%= @student.name%></p>

<div class="form-button">
<%= f.submit("Delete Student")%>
</div>
<%end%>
</center>
</body>

app/views/students/edit.html.erb
<body style="background-color:#ffff99;"><center>

<button><%=link_to("BACK TO LIST",students_path, :class => 'back-link') %></button>

<h1>Update Student</h1>
<%= form_for(@student,:url => student_path(@student),:method => 'patch')do |f|%>
<table class='table'>
<tr>
<th>Name</th>
<th><%= f.text_field(:name)%></th>
</tr><tr>
<th>Email</th>
<th><%= f.text_field(:email)%></th>
</tr>
<tr>
<th>Phone</th>
<th><%= f.text_field(:phone)%></th>
</tr>

</table>
<div class="form-buttons">
<%= f.submit("Update Subject")%>
</div>
<%end%>
</center>
</body>

app/views/students/index.html.erb
<%= react_component 'Main' %>




<body style="background-color:#ffff99;"><center>

<h1>Students</h1>
<button><%=link_to("Add new Student",'students/new',:class=>'action new')%></button>

<table class=" table table-dark " summary="Subject list" style="border:1px solid;">
<tr class="header" style="border:1px solid;">
<%# <th style="border:1px solid;">id</th> %>
<th style="border:1px solid;">name</th>
<th style="border:1px solid;">email</th>
<th style="border:1px solid;">phone</th>
<th style="border:1px solid;">Action</th>
</tr>
<h1><% @students.each %>  </h1>
<% @students.each do |student|%>
<tr style="border:1px solid;">
<%# <td style="border:1px solid;"> <%= student.id  %>
<td style="border:1px solid;"><%= student.name  %></td>
<td class='center' style="border:1px solid;"><%= student.email  %></td>
<td class='center' style="border:1px solid;"><%= student.phone %></td><br/>
<td class="action" style="border:1px solid;">
  <button> <%=link_to("Show",student_path(student.id),:class=>'action show')%></button>
  <button> <%=link_to("Edit",edit_student_path(student.id),:class=>'action edit')%></button>
   <button><%=link_to("Delete",delete_student_path(student.id),:class=>'action delete')%></button>
</td>

</tr>
<%end%>
</table>

</center>


</body>

app/views/students/new.html.erb
<body style="background-color:#ffff99;"><center>
<button><%=link_to("BACK TO LIST",'/students', :class => 'back-link') %></button>

<h1>Create Student</h1>
<%= form_for(@student,:url => students_path,:method => 'post')do |f|%>
<table class='table'>
<tr>
<th>Name</th>
<th><%= f.text_field(:name)%></th>
</tr><tr>
<th>Email</th>
<th><%= f.text_field(:email)%></th>
</tr>
<tr>
<th>Phone</th>
<th><%= f.text_field(:phone)%></th>
</tr>

</table>
<div class="form-buttons">
<%= f.submit("Create Subject")%>
</div>
<%end%>
</center>
</body>

app/views/students/show.html.erb
<body style="background-color:#ffff99;"><center>
<p style="color: green"><%= notice %></p>

<button><%=link_to("BACK TO LIST",'/students', :class => 'back-link') %></button>
<h1>Show Student</h1>
<table class='table'>
<tr>
<th>Name</th>
<th><%= @student.name%></th>
</tr><tr>
<th>Email</th>
<th><%= @student.email%></th>
</tr>
<tr>
<th>Phone</th>
<th><%= @student.phone%></th>
</tr>

</table>
</center>
</body>